### PR TITLE
FIX gzeof linking error

### PR DESCRIPTION
**Pull request by tomvand**
Fix linking error. Apparently the current version of paparazzi reverses the order of the LDFLAGS (order-dependent). This fix puts all flags in a single line.

### CODE REVIEW

**Comment by matteobarbera** [comment]
I checked out the branch and just added 
```xml
<module name="cv_opencvdemo" >
      <define name="OPENCVDEMO_CAMERA" value="front_camera"/>
      <define name="OPENCVDEMO_FPS" value="0" />
  </module>
```
to the bebop_orange_avoid. After attempting compilation with target NPS there is a linking error
```
CC /home/matteo/Documents/mavlab/paparazzi/var/aircrafts/bebop_orange_avoid/nps/modules/datalink/pprz_dl.o
CC /home/matteo/Documents/mavlab/paparazzi/var/aircrafts/bebop_orange_avoid/nps/firmwares/rotorcraft/rotorcraft_telemetry.o
CC /home/matteo/Documents/mavlab/paparazzi/var/aircrafts/bebop_orange_avoid/nps/firmwares/rotorcraft/rotorcraft_datalink.o
LD /home/matteo/Documents/mavlab/paparazzi/var/aircrafts/bebop_orange_avoid/nps/simsitl
/usr/bin/ld: cannot find -llibjpeg-turbo
/usr/bin/ld: cannot find -llibpng
/usr/bin/ld: cannot find -llibtiff
/usr/bin/ld: cannot find -lzlib
/usr/bin/ld: cannot find -ldc1394
collect2: error: ld returned 1 exit status
make[1]: *** [/home/matteo/Documents/mavlab/paparazzi/conf/Makefile.nps:89: /home/matteo/Documents/mavlab/paparazzi/var/aircrafts/bebop_orange_avoid/nps/simsitl] Error 1
make[1]: Leaving directory '/home/matteo/Documents/mavlab/paparazzi/sw/airborne'
make: *** [Makefile.ac:212: nps.compile] Error 2
make: Leaving directory '/home/matteo/Documents/mavlab/paparazzi'
```

**Comment by tomvand** [comment]
Can you try again with the following:
1. Update submodules (opencv_bebop changed)
2. In `sw/ext/opencv_bebop`, run `make clean && make`
I've set up opencv to compile the missing libraries. If this doesn't work, try installing them through apt instead...

**Comment by matteobarbera** [comment]
Installing the libs fixed the error only for ldc1394, it still cannot find the others

**Comment by tomvand** [comment]
Found the problem; it is using the wrong filenames (notice the double lib?) from earlier attempts at changing opencv_bebop. Pushing a fix asap.

**Comment by tomvand** [comment]
Ok, let's try again.

**Comment by matteobarbera** [comment]
This time it finished the compilation :) Does the fix require the manual installation of the libraries?

**Comment by tomvand** [comment]
Great! Yes it does, so we should add it to the course manual.

**Review by matteobarbera — APPROVED** [review]

**Pull request merged**
