### PR TITLE
[IMAV] merge with latest code

### PR DESCRIPTION
**Pull request by wilcoschoneveld**

### CODE REVIEW

**Comment by knmcguire** [comment]
@wilcoschoneveld where you able to figure out the bug that causes the drone to suddenly take off to the ceiling?

**Comment by wilcoschoneveld** [comment]
I think so yeah

**Comment by knmcguire** [comment]
So take off is done by setting a hover altitude and it will go there without any problem? probably good for now. I'll check the code some more and I'll merge it soon

**Comment by knmcguire** [comment]
btw, are you testing the heading function? could you add a change_heading_relative function for the flight plan? (current heading + angle to torn).

**Pull request merged**
